[package]
name = "parolrs_gui"
version = "0.1.0"
authors = ["Ogromny <ogromny@openmailbox.org>"]

[dependencies]
parolrs = { git = "https://github.com/parolrs/core" }

[dependencies.gtk]
version = "*"
features = ["v3_12"]

[dependencies.gdk-pixbuf]
version = "*"